apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-frontend
  labels:
    app: cafe-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-frontend
  template:
    metadata:
      labels:
        app: cafe-frontend
    spec:
      containers:
        - name: cafe-frontend
          image: thedarkmental06/cafe-bliss:v4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cafe-frontend-service
spec:
  selector:
    app: cafe-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
